### PR TITLE
edgar/BaseCoreProject

### PR DESCRIPTION
**Pull request by edgarquispe**
base core project with account creation example

### CODE REVIEW

**Comment by bruxita2312** [comment]
All tests were passed
image

**Review by mfuentes-ME — APPROVED** [review]
It is working fine.

**Review by bruxita2312 — APPROVED** [review]
Working fine

**Review by bhuanca10 — APPROVED** [review]
Works for me.

**Comment by edgarquispe** [comment]
thank you I will merge into develop

**Pull request merged**
